### ISSUE TITLE
瞎扯淡

### ISSUE THREAD

**Issue by TinyNiko** [LeadroyaL/JebScript#1]
通过jeb 去生成xposed 代码的思路很赞，不考虑搞个frida的？

**Comment by LeadroyaL** [comment]
我前天还和旁边小伙伴提到过这个想法，刚好也准备写一个 FastFrida，最近应该会更新。

**Comment by LeadroyaL** [comment]
Fixed in https://github.com/LeadroyaL/JebScript/commit/4c40a009bf2065e4a7b40be8a4f52c4f6c614acc
