### ISSUE TITLE
Auto generated frida scipt return state missing

### ISSUE THREAD

**Issue by bmax121** [LeadroyaL/JebScript#2]

**Comment by LeadroyaL** [comment]
麻烦把case描述的清楚一些，没有上下文我帮不到你。

**Comment by bmax121** [comment]
麻烦大佬了。
这样的，有返回值的函数hook代码没有写返回。
现在的代码是这样的：
![image](https://user-images.githubusercontent.com/12316019/82519519-79b9cf80-9b54-11ea-93f2-33817b80473f.png)

是不是应该写成这样：
![image](https://user-images.githubusercontent.com/12316019/82519196-b0dbb100-9b53-11ea-8576-eeff0700f8f8.png)

**Comment by LeadroyaL** [comment]
对你说的对，我 frida 用的很少，抱歉写错了。
